# Generated by Django 2.1.7 on 2019-03-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userphone', models.CharField(max_length=20, verbose_name='Request Phone')),
                ('crop', models.CharField(max_length=20, verbose_name='Crop')),
                ('bags', models.IntegerField(default=0, verbose_name='Number of bags')),
                ('pickup', models.CharField(max_length=30, verbose_name='Pickup Location')),
                ('destination', models.CharField(max_length=30, verbose_name='Destination')),
                ('mobile_money', models.CharField(max_length=30, verbose_name='Mobile money number')),
            ],
        ),
    ]
